<?php
/**
 * DIS MODULE USEZ LOLSPEAK,
 * U CAN USE DIS TRANZLATR IF U R NOT COMFORTABLE WIF DIS LANGUAGE
 * http://speaklolcat.com/
 * 
 * @author Kamule
 */

class Wordz{
	const MESAGEZ_SENDD		= 0;
	const MESAGEZ_RECEIVD	= 1;
	const MOUVEMENTS		= 2;
	const ACSHUNS 			= 3;
	const ANTI_CHEAT 		= 4;
	const ADMINISTRASHUN	= 5;
}

$conf = array(
	Wordz::MESAGEZ_SENDD 	=> 60,
	Wordz::MESAGEZ_RECEIVD	=> 60,
	Wordz::MOUVEMENTS 		=> 30,
	Wordz::ACSHUNS 		=> 60,
	Wordz::ANTI_CHEAT 		=> 120,
	Wordz::ADMINISTRASHUN	=> 120
);